- name: Setup the replication.config file
  template:
    src: replication.config.j2
    dest: "{{ _gerrit_dir }}/etc/replication.config"
    owner: "{{gerrit_user}}"
    mode: 0755
  notify: restart gerrit

- name: Create the .ssh folder
  file:
    path: "{{gerrit_user_home}}/.ssh"
    owner: "{{gerrit_user}}"
    mode: 0700
    state: directory

- name: Setup the SSH config file
  template:
    src: ssh.config.j2
    dest: "{{gerrit_user_home}}/.ssh/config"
    owner: "{{gerrit_user}}"
    mode: 0600
