---
- hosts: haplometrosis.rht.gluster.org
  vars:
    # default value for builders
    distribution: Centos
    version: 7
  roles:
  - role: guest_jenkins_builder_int_rht
    number: 0
  - role: guest_jenkins_builder_int_rht
    number: 1
  - role: guest_jenkins_builder_int_rht
    number: 2
  - role: guest_jenkins_builder_int_rht
    number: 3
  - role: guest_jenkins_builder_int_rht
    number: 4
  - role: guest_jenkins_builder_int_rht
    number: 5
  - role: guest_jenkins_builder_int_rht
    number: 6
  - role: guest_jenkins_builder_int_rht
    number: 7
  - role: guest_jenkins_builder_int_rht
    number: 8
  - role: guest_jenkins_builder_int_rht
    number: 9
  - role: guest_jenkins_builder_int_rht
    number: 10
  - role: guest_jenkins_builder_int_rht
    number: 11
  - role: guest_jenkins_builder_int_rht
    number: 12
  - role: guest_jenkins_builder_int_rht
    number: 13
  - role: guest_jenkins_builder_int_rht
    number: 14
  - role: guest_jenkins_builder_int_rht
    number: 15
  - role: guest_jenkins_builder_int_rht
    number: 16
  - role: guest_jenkins_builder_int_rht
    number: 17
  - role: guest_jenkins_builder_int_rht
    number: 18
  - role: guest_jenkins_builder_int_rht
    number: 19

  - role: guest_jenkins_builder_int_rht
    number: 45
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 46
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 47
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 48
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 49
    distribution: Fedora
    version: 28

- hosts: pleometrosis.rht.gluster.org
  roles:
  - role: guest_jenkins_builder_int_rht
    number: 20
  - role: guest_jenkins_builder_int_rht
    number: 21
  - role: guest_jenkins_builder_int_rht
    number: 22
  - role: guest_jenkins_builder_int_rht
    number: 23
  - role: guest_jenkins_builder_int_rht
    number: 24
  - role: guest_jenkins_builder_int_rht
    number: 25
  - role: guest_jenkins_builder_int_rht
    number: 26
  - role: guest_jenkins_builder_int_rht
    number: 27
  - role: guest_jenkins_builder_int_rht
    number: 28
  - role: guest_jenkins_builder_int_rht
    number: 29
  - role: guest_jenkins_builder_int_rht
    number: 30
  - role: guest_jenkins_builder_int_rht
    number: 31
  - role: guest_jenkins_builder_int_rht
    number: 32
  - role: guest_jenkins_builder_int_rht
    number: 33
  - role: guest_jenkins_builder_int_rht
    number: 34
  - role: guest_jenkins_builder_int_rht
    number: 35
  - role: guest_jenkins_builder_int_rht
    number: 36
  - role: guest_jenkins_builder_int_rht
    number: 37
  - role: guest_jenkins_builder_int_rht
    number: 38
  - role: guest_jenkins_builder_int_rht
    number: 39

  - role: guest_jenkins_builder_int_rht
    number: 40
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 41
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 42
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 43
    distribution: Fedora
    version: 28
  - role: guest_jenkins_builder_int_rht
    number: 44
    distribution: Fedora
    version: 28

- hosts: jenkins_builders_rht
  tasks:
  - name: Resize the disk of the builders
    lvol:
      vg: "vg_root_{{ ansible_fqdn }}"
      lv: root
      size: 18G
    when: ansible_system == 'Linux'
  - name: Make sure the filesystem is resized
    filesystem:
      fstype: ext4
      dev: "/dev/mapper/vg_root_{{ ansible_fqdn }}-root"
      resizefs: True
    when: ansible_system == 'Linux'

