---
- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    vars:
      name: webbuilder.int.rht.gluster.org
    system_disk_size: 10
    mem_size: 1024
    distribution: Centos
    version: 7
    bridge: "{{ bridge_common }}"
    network:
      ip: 172.24.1.58/24
      gateway: 172.24.1.181
