# needed later for package
- hosts: all

- hosts: backups
  roles:
  - role: backups
    vg_root: vg_data_backups.rht.gluster.org
    backups:
    - directory: /var/lib/mailman/ 
      age_max: "10D"
      size: "6G" 
      server: "supercolony.gluster.org"
      user: root
    - directory: /var/lib/jenkins/
      age_max: "20D"
      size: "1G"
      server: "build.gluster.org"
      user: "root"
    - directory: /var/backups/postgresql
      age_max: "10D"
      size: "1G"
      server: "postgresql.rht.gluster.org"
      user: root
