- hosts: myrmicinae.rht.gluster.org
  roles:
  - role: guest_virt_install
    vars:
      name: ant-queen.int.rht.gluster.org
    system_disk_size: 10
    data_disk_size: 2
    mem_size: 1024
    distribution: Centos
    version: 7
    bridge: "{{ bridge_common }}"
    network:
      ip: 172.24.1.53/24
      gateway: 172.24.1.181

- hosts: ant-queen.int.rht.gluster.org
  tasks:
  - filesystem:
      dev: /dev/vdb
      fstype: xfs
  - mount:
      path: /home/
      src: /dev/vdb
      fstype: xfs
      state: mounted
  roles:
  - role: swap_file
    size: 1G
    path: /var/swap

