- hosts: monitoring_from_inside
  roles:
  - role: munin
    munin_master: munin.int.rht.gluster.org
    munin_master_ip: 172.24.1.59
#    admin_email: root@{{ ansible_domain }}
    diskstats_exclude: "mapper_patchy_,patchy_"

- hosts: all:!monitoring_from_inside
  roles:
  - role: munin
    munin_master: munin.int.rht.gluster.org
    munin_master_ip: 8.43.85.181
#    admin_email: root@{{ ansible_domain }}
    diskstats_exclude: "mapper_patchy_,patchy_"


- hosts: munin.int.rht.gluster.org
  roles:
  - role: swap_file
    size: 1G
    path: /var/swap
