- hosts: gerrit-stage.rht.gluster.org
  roles:
  - role: cgit
    git_repositories_dir: /review/review.gluster.org/git/
    scan_path: true
  - role: xinetd_git_daemon
    base_path: /review/review.gluster.org/git
  - role: openssh_different_port
    ssh_port: 2222
  - role: gerrit
    gerrit_domain: gerrit-stage.rht.gluster.org
    gerrit_email: review@gerrit-stage.rht.gluster.org
    gerrit_home: review.gluster.org
    use_letsencrypt: True
    mail_domain: gluster.org
    website_domain: gerrit-stage.rht.gluster.org
    gerrit_replication:
    - repo: gluster-test
      github_user: gluster
      keyfile: gluster-test

