---
- hosts: pleometrosis.rht.gluster.org
  roles:
  - role: guest_virt_install
    vars:
      name: sentry.int.rht.gluster.org
    system_disk_size: 10
    mem_size: 2048
    distribution: Centos
    version: 7
    bridge: "{{ bridge_common }}"
    network:
      ip: 172.24.1.67/24
      gateway: 172.24.1.181
      nameservers:
      - 172.24.1.60
      - 172.24.1.61
