---
- hosts: postgresql.rht.gluster.org
  roles:
  - role: postgresql
    listen_addresses: "localhost,8.43.85.170"
    databases_auth:
    - name: "fstat"
      address: "8.43.85.173/32"
    - name: "gerrit"
      address: "8.43.85.171/32"
    - name: "gerrit_stage"
      address: "8.43.85.174/32"
    - name: "softserve"
      address: "8.43.85.186/32"
  - role: postgresql_backups
  tasks:
  - name: Open firewall for the internal range only
    firewalld:
      permanent: True
      immediate: True
      state: enabled
      rich_rule: 'rule family="ipv4" port port=5432 protocol=tcp source address="8.43.85.128/26" accept'


- hosts: postgresql.int.rht.gluster.org
  roles:
  - role: postgresql
    listen_addresses: "localhost,172.24.1.64"
    databases_auth:
    - name: "fstat"
      address: "172.24.1.66/32"
    - name: "softserve"
      address: "172.24.1.65/32"
  tasks:
  - name: Open firewall for the internal range only
    firewalld:
      permanent: True
      immediate: True
      state: enabled
      service: postgresql


