---
- name: Install mailman
  package:
    name: mailman
    state: present

- name: Deploy mm_cfg.py
  template:
    dest: /etc/mailman/mm_cfg.py
    src: mm_cfg.py
  notify: restart mailman

- name: Ensure the mailman service is started
  service:
    name: mailman
    state: started
    enabled: yes

- include: create_lists.yml

- include: ban_command.yml

- name: Block list creation on the web
  template:
    src: block_web_ml.conf
    dest: "{{ _vhost_confdir }}/block_web_ml.conf"
  notify: verify config and restart httpd

- include: dnsbl_blacklist.yml
  when: dnsbl_mailman 
